name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            echo "Starting deployment..."
            
            # Navigate to home directory
            cd /home/ubuntu
            
            # Check if directory exists
            if [ ! -d "fastapi-book-project" ]; then
              echo "Directory not found, cloning repository..."
              git clone https://github.com/yourusername/fastapi-book-project.git
            fi
            
            cd fastapi-book-project
            
            # Check if venv exists, create if it doesn't
            if [ ! -d "venv" ]; then
              echo "Creating virtual environment..."
              python3 -m venv venv
            fi
            
            echo "Pulling latest changes..."
            git pull
            
            echo "Activating virtual environment..."
            source venv/bin/activate
            
            echo "Installing dependencies..."
            pip install -r requirements.txt
            
            echo "Restarting FastAPI service..."
            sudo systemctl restart fastapi
            
            echo "Deployment completed successfully!"