name: CD - Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_USER: ${{ secrets.AWS_USER }}
          AWS_HOST: ${{ secrets.AWS_HOST }}
        run: |
          echo "$AWS_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem $AWS_USER@$AWS_HOST << 'EOF'
            cd fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            systemctl restart fastapi
          EOF